import { Layout } from '@/layout'
import { ReactNode } from 'react'
import { WagmiProvider} from '@/components/wallet/providers/wagmiProvider'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <WagmiProvider>{children}</WagmiProvider></Layout>
      </body>
    </html>
  )
}
